#ifndef INCLUDE_GAMEDEFINE_H_
#define INCLUDE_GAMEDEFINE_H_

enum { ROCK = 0x8001, SCISSORS = 0x8002, PAPER = 0x8004 };
enum { ROCK_PAPER = ROCK | PAPER
	 , ROCK_SCISSORS = ROCK | SCISSORS
	 , SCISSORS_PAPER = PAPER | SCISSORS
	 , ROCK_SCISSORS_PAPER = ROCK_PAPER | SCISSORS };

enum { TIGER = 0x7001, STICK = 0x7002, CHICKEN = 0x7004 };
enum { TIGER_STICK = TIGER | STICK
	 , TIGER_CHICKEN = TIGER | CHICKEN
	 , STICK_CHICKEN = STICK | CHICKEN
	 , TIGER_STICK_CHICKEN = TIGER | STICK | CHICKEN };

#endif
